### ISSUE TITLE
Continuous delivery

### ISSUE THREAD

**Issue by jlheig** [gen-classroom/projet-blanc_maillard_pozniakoff#32]
En tant que développeur, j’aimerai que la création et la publication d’une nouvelle release soit automatisée à l’aide de GitHub actions. En d’autres termes, j’aimerai que le fichier jar ou le fichier zip de la release soit publié de manière automatique lorsqu’un tag correspondant à une version (p. ex. v0.0.2) est publié sur git.

**Comment by jlheig** [comment]
Estimation du temps requis pour effectuer cette tâche : 3 heures

**Comment by pozniako16** [comment]
fais en 6h
