### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by mathias-maillard** [gen-classroom/projet-blanc_maillard_pozniakoff#35]
We need to implement unit tests

**Comment by jlheig** [comment]
Estimation du temps requis pour effectuer cette tâche : 6 heures

**Comment by jlheig** [comment]
Tests unitaire pour Clean et Build : Environ 4 heures, j'ai rencontré beaucoup de problèmes qui ont nécessité de modifier les fichiers build et clean dans d'autres branches, ce qui m'a fait perdre beaucoup de temps.

**Comment by pozniako16** [comment]
j'ai mis 4h à cause de soucis sur des tests qui impliquaient la création de fichier + des modifications suite à la mise en place du code coverage

**Comment by mathias-maillard** [comment]
Après 1h de réflexion sur les tests de la commande Serve, aucun test utile ne semblait valoir la peine d'être implémenté.
