### ISSUE TITLE
Code Quality

### ISSUE THREAD

**Issue by jlheig** [gen-classroom/projet-blanc_maillard_pozniakoff#59]
Configurez LGTM , SonarQube ou un outil équivalent pour détecter des bugs et des vulnérabilités dans votre code. Expliquez en quoi l’un de ces outils vous aura permis d’améliorer vos pratiques de développement.

**Comment by pozniako16** [comment]
Estimation: 3h

**Comment by mathias-maillard** [comment]
Installation et lecture de la documentation de LGTM: 2h
