### ISSUE TITLE
Génération du site statique à la volée

### ISSUE THREAD

**Issue by jlheig** [gen-classroom/projet-blanc_maillard_pozniakoff#61]
En tant qu’utilisateur, j’aimerai que les commandes build et serve puissent régénérer le site statique à la volée, c’està-dire de manière automatique lorsque des changements sont effectués sur le système de fichier. Pour cela, ajoutez une option --watch aux commandes build et serve et assurez-vous que leur exécution ne se termine pas à la fin du premier build. 

Les générateurs de site statique Jekyll et Hugo disposent tous deux d’une option --watch. La WatchService API de la librairie standard Java permet d’écouter les changements effectués sur le système de fichiers.
Question ouverte : Faut-il recompiler tous les fichiers lors de chaque changement ?

**Comment by pozniako16** [comment]
Estimation: 5h

**Comment by mathias-maillard** [comment]
Cette partie a pris 6 heures, en considérant qu'un certain temps a été passé à résoudre des soucis pas directement liés à cette issue
